#!/bin/bash
echo "GPU:" $(nvidia-smi -a | awk 'FNR == 10 {$1=$2=$3=""; print $0}')
echo "Power Usage:" $(nvidia-smi -a | awk 'FNR == 155 {$1=$2=$3=""; print $0}')
echo "Power Max:" $(nvidia-smi -a | awk 'FNR == 156 {$1=$2=$3=""; print $0}')

echo
echo "VRAM Used:" $(nvidia-smi -a | awk 'FNR == 78 {$1=$2=""; print $0}')
echo "VRAM Free:" $(nvidia-smi -a | awk 'FNR == 79 {$1=$2=""; print $0}')
echo "VRAM Total:" $(nvidia-smi -a | awk 'FNR == 77 {$1=$2=""; print $0}')

echo
echo "BAR Used:" $(nvidia-smi -a | awk 'FNR == 82 {$1=$2=""; print $0}')
echo "BAR Free:" $(nvidia-smi -a | awk 'FNR == 83 {$1=$2=""; print $0}')
echo "BAR Total:" $(nvidia-smi -a | awk 'FNR == 81 {$1=$2=""; print $0}')

echo
echo "GPU:" $(nvidia-smi -a | awk 'FNR == 86 {$1=$2=""; print $0}')
echo "Memory:" $(nvidia-smi -a | awk 'FNR == 87 {$1=$2=""; print $0}')
echo "Encoder:" $(nvidia-smi -a | awk 'FNR == 88 {$1=$2=""; print $0}')
echo "Decoder:" $(nvidia-smi -a | awk 'FNR == 89 {$1=$2=""; print $0}')

echo
echo "CPU:" $(lscpu | awk 'FNR == 13 {$1=$2=""; print $0}')
echo "Load Average:" $(top -b -n1 | awk 'FNR == 1 {print $11,$12,$13}')

echo
echo "Used RAM:" $(free -h --si | awk 'FNR == 2 {print $3}')
echo "Cached RAM:" $(free -h --si | awk 'FNR == 2 {print $6}')
echo "Free RAM:" $(free -h --si | awk 'FNR == 2 {print $4}')
echo "Total RAM:" $(free -h --si | awk 'FNR == 2 {print $2}')

echo
echo "Used Disk:" $(df -h / | awk 'FNR == 2 {print $3}')
echo "Free Disk:" $(df -h / | awk 'FNR == 2 {print $4}')
echo "Total Disk:" $(df -h / | awk 'FNR == 2 {print $2}')
